console.log("practice split");

/* Nutze folgenden String als Beispiel:   const futuramaQuote = "It's okay, Bender. I like cooking too. Oh, you're a dollar naughtier than most. My fellow Earthicans, as I have explained in my book 'Earth in the Balance', and the much more popular 'Harry Potter and the Balance of Earth', we need to defend our planet against pollution. Also dark wizards." */

const futuramaQuote = "It's okay, Bender. I like cooking too. Oh, you're a dollar naughtier than most. My fellow Earthicans, as I have explained in my book 'Earth in the Balance', and the much more popular 'Harry Potter and the Balance of Earth', we need to defend our planet against pollution. Also dark wizards."

const split0 = futuramaQuote.split('');
console.log(split0); /* console returns each letter: (290) ['I', 't', "'", 's', ' ', 'o', 'k', 'a', 'y', ',', ' ', 'B', 'e', 'n', 'd', 'e', 'r', '.', ' ', 'I', ' ', 'l', 'i', 'k', 'e', ' ', 'c', 'o', 'o', 'k', 'i', 'n', 'g', ' ', 't', 'o', 'o', '.', ' ', 'O', 'h', ',', ' ', 'y', 'o', 'u', "'", 'r', 'e', ' ', 'a', ' ', 'd', 'o', 'l', 'l', 'a', 'r', ' ', 'n', 'a', 'u', 'g', 'h', 't', 'i', 'e', 'r', ' ', 't', 'h', 'a', 'n', ' ', 'm', 'o', 's', 't', '.', ' ', 'M', 'y', ' ', 'f', 'e', 'l', 'l', 'o', 'w', ' ', 'E', 'a', 'r', 't', 'h', 'i', 'c', 'a', 'n', 's', …] */


const split1 = futuramaQuote.split(' ')
console.log(split1); /* console returns each word: (51) ["It's", 'okay,', 'Bender.', 'I', 'like', 'cooking', 'too.', 'Oh,', "you're", 'a', 'dollar', 'naughtier', 'than', 'most.', 'My', 'fellow', 'Earthicans,', 'as', 'I', 'have', 'explained', 'in', 'my', 'book', "'Earth", 'in', 'the', "Balance',", 'and', 'the', 'much', 'more', 'popular', "'Harry", 'Potter', 'and', 'the', 'Balance', 'of', "Earth',", 'we', 'need', 'to', 'defend', 'our', 'planet', 'against', 'pollution.', 'Also', 'dark', 'wizards.']0: "It's"1: "okay,"2: "Bender."3: "I"4: "like"5: "cooking"6: "too."7: "Oh,"8: "you're"9: "a"10: "dollar"11: "naughtier"12: "than"13: "most."14: "My"15: "fellow"16: "Earthicans,"17: "as"18: "I"19: "have"20: "explained"21: "in"22: "my"23: "book"24: "'Earth"25: "in"26: "the"27: "Balance',"28: "and"29: "the"30: "much"31: "more"32: "popular"33: "'Harry"34: "Potter"35: "and"36: "the"37: "Balance"38: "of"39: "Earth',"40: "we"41: "need"42: "to"43: "defend"44: "our"45: "planet"46: "against"47: "pollution."48: "Also"49: "dark"50: "wizards."length: 51[[Prototype]]: Array(0) */

const split2 = futuramaQuote.split('.');
console.log(split2); /* console returns each sentence: (6) ["It's okay, Bender", ' I like cooking too', " Oh, you're a dollar naughtier than most", " My fellow Earthicans, as I have explained in my b…', we need to defend our planet against pollution", ' Also dark wizards', '']0: "It's okay, Bender"1: " I like cooking too"2: " Oh, you're a dollar naughtier than most"3: " My fellow Earthicans, as I have explained in my book 'Earth in the Balance', and the much more popular 'Harry Potter and the Balance of Earth', we need to defend our planet against pollution"4: " Also dark wizards"5: ""length: 6[[Prototype]]: Array(0) */

const split3 = futuramaQuote.split(',');
console.log(split3); /* console returns splitted after each comma : (6) ["It's okay", ' Bender. I like cooking too. Oh', " you're a dollar naughtier than most. My fellow Earthicans", " as I have explained in my book 'Earth in the Balance'", " and the much more popular 'Harry Potter and the Balance of Earth'", ' we need to defend our planet against pollution. Also dark wizards.']0: "It's okay"1: " Bender. I like cooking too. Oh"2: " you're a dollar naughtier than most. My fellow Earthicans"3: " as I have explained in my book 'Earth in the Balance'"4: " and the much more popular 'Harry Potter and the Balance of Earth'"5: " we need to defend our planet against pollution. Also dark wizards."length: 6[[Prototype]]: Array(0) */

const split4 = futuramaQuote.split('B');
console.log(split4); /* console returns text with every B cutted out: (4) ["It's okay, ", "ender. I like cooking too. Oh, you're a dollar nau…ns, as I have explained in my book 'Earth in the ", "alance', and the much more popular 'Harry Potter and the ", "alance of Earth', we need to defend our planet against pollution. Also dark wizards."]0: "It's okay, "1: "ender. I like cooking too. Oh, you're a dollar naughtier than most. My fellow Earthicans, as I have explained in my book 'Earth in the "2: "alance', and the much more popular 'Harry Potter and the "3: "alance of Earth', we need to defend our planet against pollution. Also dark wizards."length: 4[[Prototype]]: Array(0) */

